### ISSUE TITLE
GetPreviewData - An unexpected exception occurred

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/DaxTemplate#36]
Running the query to preview the data raises the following error :
`An unexpected exception occurred. An unexpected exception occurred.`

Unfortunately, there are no further useful details in either the stack trace or the response received from the SSAS server.
Attached here is the PBIX and DAX query to reproduce the error.

[repro-pbix-and-dax.zip](https://github.com/sql-bi/DaxTemplate/files/10228539/repro-pbix-and-dax.zip)

**Comment by marcosqlbi** [comment]
This is a bug in Power BI Desktop December 2022 that will be fixed probably with an interim update.
However, Bravo 1.0.1 should already have a version of DaxTemplate library that changes the DAX code so that it doesn't raise this error (we used IF instead of SWITCH).
Please check that and close if confirmed that is not an issue in v1.0.1.

**Comment by albertospelta** [comment]
I confirm that this error does not happen with Bravo version 1.0.1, where we used IF instead of SWITCH. We have the same error message in some telemetry events related to periods prior to the release of Power BI Desktop December 2022 but in those cases it is probably a different error condition.
